project_id = "hpfurpylorcuvcoevpsl"

[functions.telegram-auth]
verify_jwt = false

[functions.export-bookings]
verify_jwt = false

[functions.send-telegram-export]
verify_jwt = false

[functions.daily-backup]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false